#qsub ./Integrin_part_a/submit.sh
#qsub ./Integrin_part_b/submit.sh
#qsub ./Integrin_part_c/submit.sh
#qsub ./Integrin_part_d/submit.sh
#qsub ./Integrin_part_e/submit.sh
#qsub ./Integrin_part_f/submit.sh
qsub ./Integrin_part_g/submit.sh
#qsub ./Integrin_part_h/submit.sh
#qsub ./Integrin_part_i/submit.sh
#qsub ./Integrin_part_j/submit.sh
#qsub ./Integrin_part_k/submit.sh
#qsub ./Integrin_part_l/submit.sh
#qsub ./Integrin_part_m/submit.sh
#qsub ./Integrin_part_n/submit.sh
qsub ./Integrin_part_o/submit.sh
qsub ./Integrin_part_p/submit.sh
qsub ./Integrin_part_q/submit.sh
